<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>8.0</LangVersion>
    <OutputPath>bin\Win64_Shipping_Client\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Imports handled by Directory.Build.props -->
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="LivingWorld((READ ONLY))\**" />
    <Compile Remove="**\bin\**" />
    <Compile Remove="**\obj\**" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(BannerlordLibs)\0Harmony.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Bannerlord.ButterLib">
      <HintPath>$(BannerlordLibs)\Bannerlord.ButterLib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Bannerlord.UIExtenderEx">
      <HintPath>$(BannerlordLibs)\Bannerlord.UIExtenderEx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="MCMv5">
      <HintPath>$(BannerlordLibs)\MCMv5.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.Engine">
      <HintPath>$(BannerlordLibs)\TaleWorlds.Engine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.MountAndBlade">
      <HintPath>$(BannerlordLibs)\TaleWorlds.MountAndBlade.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.CampaignSystem">
      <HintPath>$(BannerlordLibs)\TaleWorlds.CampaignSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.ModuleManager">
      <HintPath>$(BannerlordLibs)\TaleWorlds.ModuleManager.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.GauntletUI">
      <HintPath>$(BannerlordLibs)\TaleWorlds.GauntletUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.GauntletUI.Data">
      <HintPath>$(BannerlordLibs)\TaleWorlds.GauntletUI.Data.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.GauntletUI.PrefabSystem">
      <HintPath>$(BannerlordLibs)\TaleWorlds.GauntletUI.PrefabSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.Engine.GauntletUI">
      <HintPath>$(BannerlordLibs)\TaleWorlds.Engine.GauntletUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.Core">
      <HintPath>$(BannerlordLibs)\TaleWorlds.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.Core.ViewModelCollection">
      <HintPath>$(BannerlordLibs)\TaleWorlds.Core.ViewModelCollection.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.Library">
      <HintPath>$(BannerlordLibs)\TaleWorlds.Library.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.Localization">
      <HintPath>$(BannerlordLibs)\TaleWorlds.Localization.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.ObjectSystem">
      <HintPath>$(BannerlordLibs)\TaleWorlds.ObjectSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.SaveSystem">
      <HintPath>$(BannerlordLibs)\TaleWorlds.SaveSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.InputSystem">
      <HintPath>$(BannerlordLibs)\TaleWorlds.InputSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Serilog">
      <HintPath>$(BannerlordLibs)\Serilog.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Serilog.Sinks.File">
      <HintPath>$(BannerlordLibs)\Serilog.Sinks.File.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Serilog.Extensions.Logging">
      <HintPath>$(BannerlordLibs)\Serilog.Extensions.Logging.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>$(BannerlordLibs)\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging">
      <HintPath>$(BannerlordLibs)\Microsoft.Extensions.Logging.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
      <HintPath>$(BannerlordLibs)\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyInjection">
      <HintPath>$(BannerlordLibs)\Microsoft.Extensions.DependencyInjection.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.CampaignSystem.ViewModelCollection">
      <HintPath>$(BannerlordLibs)\TaleWorlds.CampaignSystem.ViewModelCollection.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.ScreenSystem">
      <HintPath>$(BannerlordLibs)\TaleWorlds.ScreenSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.TwoDimension">
      <HintPath>$(BannerlordLibs)\TaleWorlds.TwoDimension.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.DotNet">
      <HintPath>$(BannerlordLibs)\TaleWorlds.DotNet.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="SandBox">
      <HintPath>$(BannerlordLibs)\SandBox.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>



</Project>
